# CircleCI configuration file
version: 2.1

# orbs:
#   node: circleci/node@5.1.0

jobs:
  build:
    docker:
      - image: circleci/node:19.5
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: |
            npm install
      - run:
          name: Running Angular build
          command: |
            npm build

workflows:
  build_test:
    jobs:
      - build