# CircleCI configuration file
version: 2.1

# orbs:
#   node: circleci/node@5.1.0

jobs:
  # build:
  #   docker:
  #     - image: cimg/node:19.5
  #   steps:
  #     - checkout
  #     - node/install-packages
  #     - run:
  #         name: Running Angular build
  #         command: npm build

  run_tests:
    docker:
      - image: cimg/node:19.5
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install
      - run:
          name: Run Unit Tests
          command: |
            npm test
