# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:19.5
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: |
            npm install
      - run:
          name: Running Angular build
          command: |
            npm build

workflows:
  build_test:
    jobs:
      - build
